#!/usr/bin/env python3
"""Validate and publish cleaned listings generated by Hanoi aigod.

Usage:
  python3 scripts/publish_feed.py /path/to/cleaned_items.json

The input can be either a JSON list or {"items": [...]}.
The script validates, deduplicates, sorts, and writes data/listings.json.
"""
from __future__ import annotations

import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "data" / "listings.json"
ALLOWED_SECTIONS = {"property", "cooperation"}
ALLOWED_SCORES = {"A", "B"}

REQUIRED = {
    "id", "score", "section", "country", "city_region", "category",
    "direction", "title_zh", "summary_zh", "source_platform",
    "source_url", "published_at", "verification_status", "publish_status"
}


def norm(v: Any) -> str:
    return " ".join(str(v or "").strip().split())


def fingerprint(item: dict[str, Any]) -> str:
    base = "|".join([
        norm(item.get("source_url")).lower(),
        norm(item.get("contact_public")).lower(),
        norm(item.get("title_zh")).lower(),
        norm(item.get("city_region")).lower(),
    ])
    return hashlib.sha256(base.encode("utf-8")).hexdigest()


def validate(item: dict[str, Any]) -> list[str]:
    errors = []
    missing = [k for k in REQUIRED if not norm(item.get(k))]
    if missing:
        errors.append("missing=" + ",".join(sorted(missing)))
    if item.get("score") not in ALLOWED_SCORES:
        errors.append("score must be A or B")
    if item.get("section") not in ALLOWED_SECTIONS:
        errors.append("section must be property or cooperation")
    if item.get("score") == "B" and item.get("verification_status") != "待进一步核实":
        errors.append("B item must be marked 待进一步核实")
    if item.get("publish_status") not in {"published", "hidden"}:
        errors.append("publish_status must be published or hidden")
    if not str(item.get("source_url", "")).startswith(("http://", "https://")):
        errors.append("source_url must be http(s)")
    return errors


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: publish_feed.py INPUT.json", file=sys.stderr)
        return 2
    source = Path(sys.argv[1])
    raw = json.loads(source.read_text(encoding="utf-8"))
    items = raw.get("items", []) if isinstance(raw, dict) else raw
    if not isinstance(items, list):
        raise ValueError("input must be a list or an object containing items")

    clean: list[dict[str, Any]] = []
    rejected: list[dict[str, Any]] = []
    seen: set[str] = set()
    for idx, item in enumerate(items):
        if not isinstance(item, dict):
            rejected.append({"index": idx, "errors": ["not an object"]})
            continue
        errors = validate(item)
        fp = fingerprint(item)
        if fp in seen:
            errors.append("duplicate")
        if errors:
            rejected.append({"id": item.get("id", idx), "errors": errors})
            continue
        seen.add(fp)
        item["fingerprint"] = fp
        clean.append(item)

    clean.sort(key=lambda x: (x.get("score") != "A", x.get("published_at", "")), reverse=False)
    payload = {
        "updated_at": datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds"),
        "count": len(clean),
        "rejected_count": len(rejected),
        "items": clean,
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    report = ROOT / "data" / "last_publish_report.json"
    report.write_text(json.dumps({"accepted": len(clean), "rejected": rejected}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"accepted={len(clean)} rejected={len(rejected)} output={OUTPUT}")
    return 0 if not rejected else 1


if __name__ == "__main__":
    raise SystemExit(main())
